
no_claims <- "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Imh1Tjk1SXZQZmVocTM0R3pCRFoxR1hHaXJuTSIsImtpZCI6Imh1Tjk1SXZQZmVocTM0R3pCRFoxR1hHaXJuTSJ9.e30.lAN47b8E2S-tzeyAM6LJi120zXXPe6Fz75jFEPAsWSA20BOsiUjx0sNWHxA1FQ5qOViCCqXyvSOYZqUFpJcbNNVEm0-Szi_Os8mMllrGj-R336PGAvhGAcCsehZnq4abqCRt7I42iXXxsKNWiq3f8bxAF22GGz8urFV0GRAvkL4GZa5wK6pDr5LKjHsEwgkTxhLt5iOm24Lm4NBdaIVNaOwJIZiHCkceSIRMpDUGkWM7Jf6hVWW0oay5aY4B3jUpvgiHrMzrsQK-w1zZS1Xls2LaaDn_yPYwdSqgddK6zbCyaxvkitK-O7xooLbHHYlKILM5yitqiHTtVKO1_F4k2w"
out_of_date <- "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Imh1Tjk1SXZQZmVocTM0R3pCRFoxR1hHaXJuTSIsImtpZCI6Imh1Tjk1SXZQZmVocTM0R3pCRFoxR1hHaXJuTSJ9.eyJhdWQiOiJhNDBlZDA5Ny03ZTVmLTQ5MjAtOTNlYS1jNjg1NzgzODQxOGMiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC9mNjZmYWUwMi01ZDM2LTQ5NWItYmZlMC03OGE2ZmY5ZjhlNmUvIiwiaWF0IjoxNTk1MzM1OTM4LCJuYmYiOjE1OTUzMzU5MzgsImV4cCI6MTU5NTMzOTgzOCwiYWNyIjoiMSIsImFpbyI6IkFWUUFxLzhRQUFBQXJPZFE2b3ZsWWZwdW5CcEorT09aazhNSDBPZTJDVXlWZ2pkc3FyTU9VYktJc2N0ZVZGUmJXSmNxeThEYzZNdkRiN3A2cStHcGRFR2svQzVzQnU3dVFrS3VUcnFtNmhnd3JkckNFbzBCR0JBPSIsImFtciI6WyJwd2QiLCJtZmEiXSwiYXBwaWQiOiI3ZjU1ZmM2OS03ZWJlLTQ5ZGUtYmZjYy1lNWI3ZDFjNjI3ODYiLCJhcHBpZGFjciI6IjAiLCJmYW1pbHlfbmFtZSI6IldoaXRlIiwiZ2l2ZW5fbmFtZSI6IlN0dWFydCIsImlwYWRkciI6IjIuMjE4LjEwMS4xNDkiLCJuYW1lIjoiV2hpdGUsIFN0dWFydCIsIm9pZCI6IjE3ZGMxM2NjLWQyYzgtNGU0Ny1iNjMzLTcwODY4MWNkODQ4MSIsIm9ucHJlbV9zaWQiOiJTLTEtNS0yMS0xNzE1NTY3ODIxLTE2NTkwMDQ1MDMtODM5NTIyMTE1LTIxMzA2NzgiLCJyaCI6IjAuQVF3QUFxNXY5alpkVzBtXzRIaW1fNS1PYm1uOFZYLS1mdDVKdjh6bHQ5SEdKNFlNQU5JLiIsInNjcCI6Im1tZSB1c2VyX2ltcGVyc29uYXRpb24iLCJzdWIiOiIwTXBDaEZTZy1zOVBsdUVFMVZEcF9oWXl2UDB4QjEta1phOS1EZXJUUFFjIiwidGlkIjoiZjY2ZmFlMDItNWQzNi00OTViLWJmZTAtNzhhNmZmOWY4ZTZlIiwidW5pcXVlX25hbWUiOiJTdHVhcnQuV2hpdGVAdW5pbGV2ZXIuY29tIiwidXBuIjoiU3R1YXJ0LldoaXRlQHVuaWxldmVyLmNvbSIsInV0aSI6Ijlra2Y5amNkb1V5dkY0MkdBd1lhQUEiLCJ2ZXIiOiIxLjAifQ.lAN47b8E2S-tzeyAM6LJi120zXXPe6Fz75jFEPAsWSA20BOsiUjx0sNWHxA1FQ5qOViCCqXyvSOYZqUFpJcbNNVEm0-Szi_Os8mMllrGj-R336PGAvhGAcCsehZnq4abqCRt7I42iXXxsKNWiq3f8bxAF22GGz8urFV0GRAvkL4GZa5wK6pDr5LKjHsEwgkTxhLt5iOm24Lm4NBdaIVNaOwJIZiHCkceSIRMpDUGkWM7Jf6hVWW0oay5aY4B3jUpvgiHrMzrsQK-w1zZS1Xls2LaaDn_yPYwdSqgddK6zbCyaxvkitK-O7xooLbHHYlKILM5yitqiHTtVKO1_F4k2w"
in_date_no_iss <- "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Imh1Tjk1SXZQZmVocTM0R3pCRFoxR1hHaXJuTSIsImtpZCI6Imh1Tjk1SXZQZmVocTM0R3pCRFoxR1hHaXJuTSJ9.eyJpYXQiOjE1OTUzMzU5MzgsIm5iZiI6IDE1OTUzMzU5MzgsImV4cCI6IDMyNTIxMDAzOTMyfQ.lAN47b8E2S-tzeyAM6LJi120zXXPe6Fz75jFEPAsWSA20BOsiUjx0sNWHxA1FQ5qOViCCqXyvSOYZqUFpJcbNNVEm0-Szi_Os8mMllrGj-R336PGAvhGAcCsehZnq4abqCRt7I42iXXxsKNWiq3f8bxAF22GGz8urFV0GRAvkL4GZa5wK6pDr5LKjHsEwgkTxhLt5iOm24Lm4NBdaIVNaOwJIZiHCkceSIRMpDUGkWM7Jf6hVWW0oay5aY4B3jUpvgiHrMzrsQK-w1zZS1Xls2LaaDn_yPYwdSqgddK6zbCyaxvkitK-O7xooLbHHYlKILM5yitqiHTtVKO1_F4k2w"
in_date_ok_bad_sig <- "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJhNDBlZDA5Ny03ZTVmLTQ5MjAtOTNlYS1jNjg1NzgzODQxOGMiLCJpYXQiOjE1OTUzMzU5MzgsIm5iZiI6MTU5NTMzNTkzOCwiZXhwIjozMTU5NTMzOTgzOCwiYXBwaWQiOiI2NWVmZWYzNS1iOGE5LTQwM2QtYThmYi0xZDc3ZWNlOWUyODQifQ.0pXhXQO4eTb-mKWe5MT2ZBEZ7CVPt9_Z1wPvf9P6uFE"

test_that("BaseAuth is not valid with no token", {
  expect_false(BaseAuth(Environment$DEV)$is_valid(NULL))
})

test_that("BaseAuth is not valid with empty token", {
  expect_false(BaseAuth(Environment$DEV)$is_valid(""))
})

test_that("BaseAuth is not valid with a non JWT token", {
  expect_false(BaseAuth(Environment$DEV)$is_valid("Not a JWT"))
})

test_that("BaseAuth is not valid with claimless token", {
  expect_false(BaseAuth(Environment$DEV)$is_valid(no_claims))
})

test_that("BaseAuth is not valid with a expired token", {
  expect_false(BaseAuth(Environment$DEV)$is_valid(out_of_date))
})

test_that("BaseAuth is not valid with in time token but no iss", {
  expect_false(BaseAuth(Environment$DEV)$is_valid(in_date_no_iss))
})

test_that("BaseAuth is not valid with in time token and bad claims", {
  expect_false(BaseAuth(Environment$QA)$is_valid(in_date_ok_bad_sig))
})

test_that("BaseAuth is valid with in time token and bad sig", {
  expect_true(BaseAuth(Environment$DEV)$is_valid(in_date_ok_bad_sig))
})
